### PR TITLE
Update subscription_services_tos.md

### PR DESCRIPTION
**Pull request by DreaAlexandre**
Correction for first bullet in "You are Responsible for the Consequences of Your Use of the Service. Removed "Conditions of Use" reference (old AUP title) and replaced with "Acceptable Use Policy" with hyperlink.

### CODE REVIEW

**Comment by peiying2** [comment]
Every PR needs at least one peer review and approval before merging. I didn't realize this is different from [Craig's](https://github.com/mozilla/legal-docs/pull/2082) for the same content change.

**Comment by DreaAlexandre** [comment]
My apologies if I made this messy. I thought I’d duplicated an effort
already underway and didn’t want to have folks looking at the same thing
twice.

**Comment by peiying2** [comment]
We will sort it out when @flodolo  is back online.

**Comment by flodolo** [comment]
Nothing to do at this point, the change seems correct.

I've set a rule to enforce review on pull requests, let's see if that helps avoiding this in the future.

**Pull request merged**
