### PR TITLE
Update mdn legal docs

### PR DESCRIPTION
**Pull request by caugner**
(MP-250)

### CODE REVIEW

**Review by aroybalreid — APPROVED** [review]
Looks good from the legal side.

**Review by mafeld — APPROVED** [review]

**Comment by caugner** [comment]
@aroybalreid @mafeld Do we need to bump the version numbers at the top? :)

- https://github.com/mozilla/legal-docs/blob/e41200c63f5d41b7da395913ea346200199e652e/en/mdn_plus_privacy.md?plain=1#L3-L4
- https://github.com/mozilla/legal-docs/blob/e41200c63f5d41b7da395913ea346200199e652e/en/mdn_plus_terms.md?plain=1#L3-L4

**Comment by aroybalreid** [comment]
Yes - please update the version numbers.  Thanks!

**Comment by flodolo** [comment]
Note that someone needs to [file a request](https://mozilla-hub.atlassian.net/wiki/spaces/FDPDT/pages/11046970/Request+a+legal+document+translation) to get the updates translated across all languages.

**Pull request merged**
