### PR TITLE
Updating the Thunderbird Privacy Notice

### PR DESCRIPTION
**Pull request by litkaemily**
Update to the Thunderbird Privacy Notice to reflect its data collection and protection practices as of August 10, 2020

cc @peiying2 does this look OK?

### CODE REVIEW

**Comment by litkaemily** [comment]
I have a few changes to make. Also, reviewing in staging -- the text format and page format is different for Thunderbird. Do you know why?

**Comment by litkaemily** [comment]
I made changes directly to the doc, but I'm not sure where they are reflected since this is now closed.

**Comment by peiying2** [comment]
The last update was from 9 years ago, before any of us started at Mozilla. Format change evolved over the years but no one touched it until it needs a content update. Feel free to make proper changes so it has the same look and feel as the rest of the legal docs.

**Comment by peiying2** [comment]
As pmac mentioned in the call, once it is merged (the only way to view the changes on Staging), if more changes are to make, you need to start a new PR. Once you start a new PR, you can view the basic format layout from "preview".

**Comment by litkaemily** [comment]
I need to reopen this pull request, please. I need to make further changes to the document.

**Pull request merged**
