### PR TITLE
Do not hardcode en-US in pl version links

### PR DESCRIPTION
**Pull request by splewako**

### CODE REVIEW

**Comment by peiying2** [comment]
splewako, is this a source file issue or just pl issue?

**Comment by splewako** [comment]
That would depend whenever there is policy about using language codes in links. Right now, I see both forms (with explicit locale part and without it/redirecting).

**Comment by splewako** [comment]
@peiying2 - is there a problem with that pr?

**Comment by peiying2** [comment]
Should I merge the pull request? 

On hard coded or not, if we can provide feedback to the lawyers who draft the files, then they can write it correctly. Can they assume all URLs will be redirected?

**Comment by splewako** [comment]
Redirects for changed links in this PR work and it would be great if we could start seeing linked pages in Polish.

I think someone working closely with the site should be asked whenever all the pages are redirected to the localized versions based on browser locale (when locale code is missing in URL). Maybe @flodolo could answer that?

**Comment by flodolo** [comment]
Links pointing to mozilla.org or support.mozilla.org should never have explicit locale codes, they'll be redirected automatically to the more appropriate locale. Stefan's change is absolutely correct.

**Comment by peiying2** [comment]
If this is more widespread, then there is need to correct the English doc, not just this one, but all the others as well.

**Comment by pdehaan** [comment]
@peiying2 I think this is more widespread. I did a quick search and found about 76 results for [en-us](https://github.com/mozilla/legal-docs/search?l=markdown&q=en-us&type=Code&utf8=%E2%9C%93) on GitHub. I think most of those could be removed and let mozilla.org auto-choose the locale.
Unfortunately, I can't see how to easily search in specific folders for strings using GitHub, but the 3-4 locales I spot checked for WebRTC_PrivacyNotice/{{locale}}.md had the same /en-us/ issue as the /pl/ locale issue above.

**Pull request merged**
