### PR TITLE
Remove obsolete documents (Firefox Lite) and translations

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Review by peiying2 — APPROVED** [review]
Looks good to me.

**Comment by peiying2** [comment]
@mafeld could you review and approve this PR?

**Review by mafeld — APPROVED** [review]

**Comment by flodolo** [comment]
Thanks both 👍🏼 

I'll merge this, but don't push it to production for now. Mostly want to make sure nothing breaks badly.T

**Comment by pmac** [comment]
In https://github.com/mozilla/bedrock/pull/11644 we went ahead and removed the old Firefox Lite URLs since they now 404 anyway with the docs gone. But it got me wondering if we shouldn't have redirected them instead somewhere, or even archived an old version?

**Pull request merged**
