### PR TITLE
FxOS PN Change (Initial Activation Ping)

### PR DESCRIPTION
**Pull request by GeoffPiperMZ**
Clarifying the description of what the Initial Activation ping is used for by Mozilla.

### CODE REVIEW

**Comment by kyoshino** [comment]
Should this be pushed to production today along with other changes?

**Comment by GeoffPiperMZ** [comment]
Hey Kohei! Thanks. I think mine on FxOS (Initial Activation) are the only
ones right now but please make those live yes :)

**Comment by kyoshino** [comment]
Looks like production has not been updated since March 26 so there are many changes: https://github.com/mozilla/legal-docs/compare/21758916986f033b4368f6311b0acbc2bdbeb0dd...master 

Anyway I'll send a pull request to have this change!

**Comment by kyoshino** [comment]
It's live: https://www.mozilla.org/en-US/privacy/firefox-os/

**Comment by GeoffPiperMZ** [comment]
Excellent and thanks for the fast turn around!

**Comment by kyoshino** [comment]
:smile_cat:

**Pull request merged**
