### PR TITLE
Correct URL typo

### PR DESCRIPTION
**Pull request by clouserw**
Bad URL: https://support.mozilla.org/kb/extension-recommendationss

This PR fixes the last part of https://github.com/mozilla/fxa/issues/2777

### CODE REVIEW

**Comment by peiying2** [comment]
@clouserw please go ahead and merge. I will notify bedrock team to make a production push.

**Comment by clouserw** [comment]
This is for FxA

Also, I don't have push permissions here.  Please land if you're able.  Thanks :)

**Comment by peiying2** [comment]
> Also, I don't have push permissions here. Please land if you're able. Thanks :)

You taught me and Mika how to use GH and how to create md docs, I thought you had higher access to this and many others. Thanks for all the lessons and patience.

**Pull request merged**
