### PR TITLE
Merged new changes

### PR DESCRIPTION
**Pull request by litkaemily**

### CODE REVIEW

**Comment by litkaemily** [comment]
@pmac and @peiying2 I need to merge pull requests #1552 and #1553 - I want to double check that it's OK to merge the others also?

**Comment by pmac** [comment]
We're going to set a date for the restructure in #1502 so that others will be ready. Other than that one you can continue to do what you need to as normal. I'll update #1502 as needed when changes merge to master.

**Comment by litkaemily** [comment]
Great, thanks! So to confirm, it's OK if I merge the pull request, which will include 1502 (I think)?

**Comment by pmac** [comment]
This PR does not include #1502. It has not merged to master so it should still be isolated. All you're doing here is merging the latest updates in the `master` branch into the `prod` branch, which is fine.

**Comment by litkaemily** [comment]
ok, thank you! just don't want to mess anything up here :) I appreciate it!

**Pull request merged**
