### PR TITLE
Update en-US.md

### PR DESCRIPTION
**Pull request by mafeld**

### CODE REVIEW

**Comment by peiying2** [comment]
We need @pmac to push this to production.

**Comment by peiying2** [comment]
@mafeld please comment when you need the doc on production.

**Comment by mafeld** [comment]
Can we push this change today or tomorrow?

**Comment by pmac** [comment]
Change has been merged and [deployed to our dev instance](https://www-dev.allizom.org/en-US/privacy/firefox-reality/). It should be in production soon.

**Pull request merged**
