### PR TITLE
Add automation to generate PDF documents

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
@clouserw 

I can't tag you as reviewer, but it would be great if you could take a look.
1. This creates a PDF subfolder in the LOCALE folder, and keep the original filename.
2. The list of files to convert is in a separate JSON file.
3. Automation runs on any push on the default branch, and opens a pull request for review. Not sure if it'll get noisy with binary files, i.e. changing when the content doesn't actually change, but I don't think there's much to do against that.

You can see the resulting PDFs in this pull request in my fork
https://github.com/flodolo/legal-docs/pull/1

I'm not using the same code as in the current FxA bash script, but Python code based on the Bedrock md->HTML conversion (the benefit is that we fix the anchors being displayed in the PDF).

BTW, I've encountered an issue with the Chinese conversion (fixed by installing additional fonts). Turns out the current FxA code is affected as well, but nobody noticed it ([example](https://github.com/mozilla/fxa/blob/main/assets/legal/mdn_plus_terms.zh-CN.pdf)).

**Comment by flodolo** [comment]
One more thing: I've excluded PDF from the push to production, i.e. these files are not in the `prod` branch.

If you want to used the repo cloned via package.json, I [did suggest](https://github.com/mozilla/fxa/issues/12902#issue-1238840598) to use `prod` as reference in this issue, so maybe we need them there too?

**Comment by flodolo** [comment]
> If we are going to use `prod`, yeah, we'd need them there too. What's the `prod` branch for?

* `main` gets published to https://www-dev.allizom.org/
* `prod` gets published to https://www.mozilla.org

It's not uncommon for changes to be stage on `main` for a bit, before getting published, that's why I suggested to reference that for the HTML stuff in FxA.

I'm going to revert the change to the _publish to prod_ workflow to include PDF files then.

@pmac 
Any concern on your side in having these PDFs as part of the repo?

If there are none, I can merge and have the PDF generated, so that FxA can make changes on their side.

**Comment by pmac** [comment]
No objections here. Bedrock should continue only importing the .md files just fine. I'll keep an eye on it though. Thanks for the heads-up.

**Pull request merged**
