### PR TITLE
Update firefox_privacy_notice.md

### PR DESCRIPTION
**Pull request by smtiernan**
Update language under Search Queries on search provider royalties

### CODE REVIEW

**Comment by flodolo** [comment]
Does this require an update to the effective date?

```
*Effective June 30, 2023*
{: datetime="2022-06-30" }
```

**Comment by smtiernan** [comment]
Yes, could you please update the effective date?

Is it possible to set the effective date to when the change goes into
production? (This is my first time making a change here on GitHub so I'm
still learning how this all works - thanks!)

Shizuka

**Comment by flodolo** [comment]
I can update the effective date, the question is: do we want to localize these documents, and use a date in the future (e.g. August 7th), so that we can publish them together, or do we want to publish the English update right away? If the latter, I can put today (or tomorrow) as date and publish.

@mafeld mentioned some updates to these doc, so we're already have one pending update in need of translation. In case, the process to request translation is [described here](https://mozilla-hub.atlassian.net/wiki/spaces/FDPDT/pages/11046970/Request+a+legal+document+translation).

**Comment by smtiernan** [comment]
Hi,
If you could push the English update first, that would be great. I will go
ahead and request translation in the meantime.

Thanks,
Shizuka

**Review by flodolo — APPROVED** [review]

**Pull request merged**
