### PR TITLE
Restructure the repo to use locale directories

### LINKED ISSUE #1501: Restructure Legal doc repo
Goal: 
- Reorganize the repo, changing from doc/locales to locale/docs, like most other product and project repos.
- Benefits: 
  - Allow legal team to create `en-US` specific content when the content is not intended for localization
  - `en` is the source for content to be localized. 
  - Conform to the standard of repo structure like others, which allows easy configuration to connect with l10n vendor platform. This connection allows automated content pull and push without too much manual manipulations. 

Review current asset:
- Identify products and projects that are integrated with legal repo; contact the teams and involve them in the transition.
[x] Common Voice: [Privacy](https://commonvoice.mozilla.org/privacy) and [Terms](https://commonvoice.mozilla.org/terms) - Jenny (can be implemented on short notice)
[x] [FxA](https://accounts.firefox.com/legal/): https://jira.mozilla.com/browse/FXA-2699 - Wil (can implement in Dec)
[x] [Hubs](https://hubs.mozilla.com/) - Liv (can be done on short notice)
- Identify docs to products that are EOLed, and should be archived:
[x] See Emily's [comment](https://github.com/mozilla/legal-docs/issues/1501#issuecomment-719043386) 

Create a branch to reflect the new structure
[x] Create a branch in legal repo and rearrange the files accordingly
[x] Create a branch in Bedrock and update relevant files accordingly to reflect the new structure.

QA the flow
[ ] Test the flow and confirm it works
[ ] Share info with teams with direct integration and allow time for them to make necessary changes.

 Switch to new structure

Special asks - nice to have, :).
[ ] CI automation
[ ] Metadata file that shows which doc is localized in which languages. Example: https://github.com/mozmeao/www-l10n/tree/master/metadata
[x] Standardize file name convention (Title case vs. lower case, etc).

### PR DESCRIPTION
**Pull request by pmac**
This moves files from `doc_name/locale.md` to `locale/doc_name.md` and standardizes the `doc_name` format to [snake case](https://en.wikipedia.org/wiki/Snake_case).

Fix #1501

### CODE REVIEW

**Review by peiying2 — COMMENTED** [review]
Looks good. Comment and observation:
- *_privacy_notice.md vs *_privacynotice.md. The latter is a minority (3 docs). Not sure if we want to standardize them now and if so would break codes. 
- Docs created for markets outside of US. Should we change the `en-US` of these docs to `en` now or later? Klar (en-DE); Cliqz (en-US), Firefox Lite for example. There might be more, need legal team's help on this.
- Are we going to create an `en` directory now to copy some en-US docs over.  This requires legal team to review the current legal docs to determine.

**Comment by pmac** [comment]
We can move all of the `en-US` docs into `en` if that's okay, then reserve `en-US` for US-specific things in the future. I just don't know if some of these docs are already US-specific.

**Comment by peiying2** [comment]
> We can move all of the `en-US` docs into `en` if that's okay, then reserve `en-US` for US-specific things in the future. I just don't know if some of these docs are already US-specific.

Or we can make a copy of `en-US` content to `en` directory. Legal can confirm later on which one is en-US only. Basically I try to emulate the mozilla.org model. There are more pages on the en-US site than any other locales. Only those that are for localization, an `en` version is created. I think the file analysis in the other PR which shows which doc has `en-US` and which ones have more than that. That gives use a clue.

Do you want to remove the EOLed docs from the initial list before you change the file names? Whatever is easy for you.

**Comment by peiying2** [comment]
> We can move all of the `en-US` docs into `en` if that's okay, then reserve `en-US` for US-specific things in the future. I just don't know if some of these docs are already US-specific.

Or we can make a copy of `en-US` content to `en` directory. Legal can confirm later on which one is en-US only. Basically I try to emulate the mozilla.org model. There are more pages on the en-US site than any other locales. Only those that are for localization, an `en` version is created. I think the[ file analysis you generated](https://github.com/mozilla/legal-docs/issues/1501#issuecomment-717520942 )which shows which doc has `en-US` and which ones have more than that. That gives use a clue.

Do you want to remove the EOLed docs from the initial list before you change the file names? Whatever is easy for you.

**Comment by pmac** [comment]
I need to make sure that the EOL'd docs are no longer in use on the site.

As for `en` vs `en-US`, I'm happy either way, but I don't want there to be duplicate files in the system, so I say we go for one or the other for now, and then add in where needed. So I vote to move them all to just `en` and add docs for `en-*` when needed.

**Comment by pmac** [comment]
I just moved all of `en-US` to `en` so we can see what it looks like.

**Comment by peiying2** [comment]
Would you incorporate Emily's comment on obsolete products: https://github.com/mozilla/legal-docs/issues/1501#issuecomment-719043386 so we can see what's left of it. And archived docs? Not sure how to organize/separate the Live products from the rest. 

Also, we can change `en-US_b` to `en_b`. The content is for smaller locales we don't want to keep updating. The doc basically points back to `en` now.

**Comment by pmac** [comment]
> Would you incorporate Emily's comment on obsolete products: [#1501 (comment)](https://github.com/mozilla/legal-docs/issues/1501#issuecomment-719043386) so we can see what's left of it. And archived docs? Not sure how to organize/separate the Live products from the rest.

I can do that except for the one I mentioned is still in use on the site. I don't know what mafeld is referring to for the archive. They all exist in this repo in the git history, but I don't know if that's enough.

> Also, we can change `en-US_b` to `en_b`. The content is for smaller locales we don't want to keep updating. The doc basically points back to `en` now.

Sure.

**Comment by pmac** [comment]
Updated the PR with the EOL docs removed and the `en_b` locale.

**Comment by peiying2** [comment]
@mafeld @litkaemily I created this spreadsheet based on the result in this PR: https://docs.google.com/spreadsheets/d/1-InfJxONhNVhX_w1cpABllgpGCCDg_h3lq1oXkSFsr8/edit#gid=0. I highlighted the docs that I don't know where the docs are used. 
- Since you listed the docs that are obsolete, I assume you know where these docs are used. Let's list the URLs of the highlighted docs so we can attempt to reach out to the owners about the change.
- Firefox Lite - this is on mobile right? How are the docs integrated and who is tasked to maintain them now?
- FxA Terms of Use? Which doc in this list is for FxA?
- Partner related docs - they were updated 3 years ago.

@pmac a few more asks or consider:
- `en-DE`, let's change to `en` as it fits the purpose of the `en` content.
- `focus` privacy notice, let's change to `firefox_focus` to be consistent with other firefox_* docs
- If you can help with identifying any of the above docs and output locations, I would appreciate it.

**Comment by peiying2** [comment]
Re-checked with the teams with direct implementations to the repo and their status:
- Common Voice: already connecting to the current branch. Should be quick and easy with any updates
- Hubs: should be simple as there is no localization involved. 
- FxA: needs to be part of a sprint, which has been planned out till Jan. Wil will check with team in their weekly meeting on the time needed to make the change. Maybe able to implement the updates by end of the year.

**Comment by peiying2** [comment]
We are updating some docs which are tracked through [bug 1666941](https://bugzilla.mozilla.org/show_bug.cgi?id=1666941)

**Comment by peiying2** [comment]
@pmac we have completed the legal docs update in the localized versions. I will be around next week before the holiday break. The three teams with direct integration said they would respond to any changes on their end, with simple fix. If you think we should wait until the first thing next year, I am ok with that.

**Comment by pmac** [comment]
I think we'll have to. I'm off work until the first week of Jan. Let's do it then. 👍

**Comment by peiying2** [comment]
> I think we'll have to. I'm off work until the first week of Jan. Let's do it then. 👍

Thank you so much for your help. We will resume in Jan!

**Comment by peiying2** [comment]
Update on the Firefox Lite docs. Three of them point to mozilla.org site, one is hard coded into the mobile app. This means, all four docs (rows 11-14) can be migrated into the new structure without the product team doing extra work. We can move to the next step as soon as we are ready. We just need to let three teams know when this is going to happen so they can update their codes around the same time (CV, FxA, Hubs)

**Comment by pmac** [comment]
> We can move to the next step as soon as we are ready. We just need to let three teams know when this is going to happen so they can update their codes around the same time (CV, FxA, Hubs)

I'm ready when you are then. I'll update this PR with the current changes in the master branch.

**Comment by peiying2** [comment]
> > We can move to the next step as soon as we are ready. We just need to let three teams know when this is going to happen so they can update their codes around the same time (CV, FxA, Hubs)
> 
> I'm ready when you are then. I'll update this PR with the current changes in the master branch.

I am ready. I assume there are no automatic updates to the products of the teams mentioned above. We inform them after you complete the migration? Or do we give them the date of the switch? Let me know how I can coordinate.

**Comment by pmac** [comment]
It sounded like maybe we needed to give them a date. Can you set that up? I'm pretty swamped with marketing org planning this week.

**Comment by pmac** [comment]
For future reference should anyone else need to do this: To keep this branch up-to-date with the master branch if more changes land there the following is the procedure I use:

1. Checkout the `restructure` branch.
2. Remove the HEAD commit: `git reset --hard @^1`
3. Run the script: `python restructure.py`
4. Commit the changes: `git add . && git commit -m "Restructure the repo to use locale directories"`
5. Push the changes back to the `restructure` branch using a force push: `git push -f origin`

**Comment by peiying2** [comment]
> It sounded like maybe we needed to give them a date. Can you set that up? I'm pretty swamped with marketing org planning this week.

CV and FxA are flexible and can implement their code changes as soon as you are done. I am waiting for Hubs' reply but some people are still on holiday break. I expect to hear back next week.

**Pull request merged**
