### PR TITLE
Update en-US.md per bug 1535217

### PR DESCRIPTION
**Pull request by peiying2**
https://docs.google.com/document/d/1_5SajuY6cBgoQA1UoXAc_nwU5KvUPqNyV6mkcy-WTUU/edit?ts=5c892d20

### CODE REVIEW

**Comment by peiying2** [comment]
@pmac This doc needs to go live tomorrow Friday, March 15. The doc is approved by product and legal teams. Take another look. We need a push of this doc today. Let me know if I should file a bug on this. The request comes from this https://bugzilla.mozilla.org/show_bug.cgi?id=1529864.

**Comment by pmac** [comment]
Thanks @peiying2. I'll file an issue with bedrock and submit a PR there. Do you expect these changes to merge soon?

**Comment by peiying2** [comment]
@pmac, If you are good with the doc, we can merge. It's you or me. I also have two other legal docs (en-US) that are updated, they can go live tomorrow. I think you should be able to see what's changed since your last push. There are a few localized versions here. We can lump them together in the same PR.

**Comment by pmac** [comment]
I don't see any issues with the changes. I'll merge then file a PR for bedrock. Thanks!

**Pull request merged**
