### PR TITLE
Final fix for anchors in Rocket privacy policy

### PR DESCRIPTION
**Pull request by pmac**
I did it wrong last time.

### CODE REVIEW

**Comment by pmac** [comment]
@peiying2 my apologies. I messed up that last PR :( I've triple checked that this is right. Mind taking one last look and merging this?

**Comment by peiying2** [comment]
Looks good. I will take note on the formatting of this moving forward. I created the en-US.md based on the revised gdoc, which doesn't have the correct format so that is the root cause of all of this. Hopefully this will do! Thank you!

**Comment by pmac** [comment]
Thanks again @peiying2! I found the docs for the rules for these attributes:

https://python-markdown.github.io/extensions/attr_list/

It's a little confusing in that it has to be on its own line for block elements (paragraphs, list items, etc), but on the same line for headers :( I'm going to try to put some automated tests together to catch these things so we don't have to worry about it as much.

**Comment by peiying2** [comment]
@pmac Thank you for the docs. I may have screwed up the docs for Common Voice. I need to check on those.

**Pull request merged**
