### PR TITLE
Revert "Move all bn-BD.md files to bn.md and remove bn-IN.md"

### PR DESCRIPTION
**Pull request by peiying2**
@pmac Reverts mozilla/legal-docs#1271 Don't mean to merge it now. It needs to wait for bn version on mozilla.org to be established before this can be merged. If it is not the case. We can merge.  Sorry about it.

### CODE REVIEW

**Comment by pmac** [comment]
I think all that needs to happen in bedrock is for "bn" to be added to the list of prod languages, and the other two "bn-*" versions to be removed right? Or is there still work to be done in the l10n repo?

**Comment by peiying2** [comment]
@pmac flod said mozilla.org is ready to move to bn with bn-BD and bn-IN still in place. Only after bn is on production and proven working. We can push the bn out as soon as that is complete or at the same time. I don't know how you want to time it. Should we keep the other two locales around to do the same? I don't think anyone will be checking legal docs all that much.

**Comment by pmac** [comment]
@peiying2 I've merged flod's changes and the update to legal-docs into bedrock, so both of those should go live at the same time and we shouldn't see any issues in theory. So I think we don't need this PR and we should be good to go with the next production push. I'll let you know when it goes live.

**Comment by peiying2** [comment]
Great!! Once that is done, I will close this PR.

**Comment by peiying2** [comment]
Close the PR since everything went smoothly, :).

**Pull request closed without merging**
