### PR TITLE
Update en-US.md

### PR DESCRIPTION
**Pull request by GeoffPiperMZ**
Changes for the upcoming Snippets (SMS) campaign, Default Search inclusion (mainly related to Yahoo etc.), and SSL Errors reporting info

### CODE REVIEW

**Comment by ckprice** [comment]
r+ for grammar/spelling.

@kyoshino can we merge?

**Comment by kyoshino** [comment]
I don't have a privilege here, @mikaland2 @peiying2 or someone?

**Comment by kyoshino** [comment]
Ah was almost mid-air collision :) Thank you @mikaland2

**Comment by kyoshino** [comment]
https://github.com/mozilla/bedrock/pull/2720 will merge this change to www.mozilla.org

**Pull request merged**
