### PR TITLE
[FxLite][TermsOfUse] 1. "contact" link. 2. Add link to sumo article (URL not final yet)

### PR DESCRIPTION
**Pull request by chianger**
@mafeld  could you review this?

Apology for the late coming change, and the SUMO link not yet confirmed. 
It's not impacting the l10n work, is it? @peiying2

### CODE REVIEW

**Comment by mafeld** [comment]
It looks like that link takes me to a page that says I've already completed the survey. Is that an error?

**Comment by peiying2** [comment]
> It looks like that link takes me to a page that says I've already completed the survey. Is that an error?

Yes, I see the same thing so I went to the Survey page: https://app.surveygizmo.com/builder/build/id/5279240 - it is actually empty other than the Thank You page which is usually the last page. Are we building this survey at the moment?

**Comment by peiying2** [comment]
@mafeld if everything else is good, we can approve this so l10n can (try to) keep the current schedule. The content must be completed by Thursday so they can be launched on Friday Asia time. Otherwise we are going to be late. We may have to fix the link post translation if it is going to be different.

**Comment by mafeld** [comment]
Yes. Otherwise looks good.

**Pull request merged**
