### PR TITLE
Delete files when pushing ALL to prod

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
@pmac 

Is the package.json file currently in the root actually used (or useful)? Should we remove it?

**Comment by flodolo** [comment]
Note: the linter failure is expected. We're waiting for a translation delivery from the vendor next week which will fix it.

**Comment by pmac** [comment]
> Is the package.json file currently in the root actually used (or useful)? Should we remove it?

I don't know. Looks like @pdehaan added it years ago. I've no idea if anyone still installs this via NPM. I know that my team doesn't need it.

**Review by pmac — APPROVED** [review]
👍

**Pull request merged**
