### PR TITLE
Updates for Firefox 56 privacy notice

### PR DESCRIPTION
**Pull request by eleemoz**

### CODE REVIEW

**Comment by peiying2** [comment]
@eleemoz this fix works but what about the localized versions?  We need to rename the current ones as *old* and the new ones taking their current place.  Once launched, we should remove the old ones.  But the ones that are not updated this time and the new ones will be mixed up even though they have different content.

**Comment by peiying2** [comment]
@eleemoz this fix works but what about the localized versions?  We need to rename the current ones as *old* and the new ones taking their current place.  Once launched, we should remove the old ones.  But the ones that are not updated this time and the new ones will be mixed up even though they have different content.

**Comment by eleemoz** [comment]
Hi @peiying2, I think all we need to do is create a tag before overwriting the localized versions. We don't need to rename them all to .old. I only did that for en-US because I wanted both easily accessible in the master branch while the old version was still live.

@alexgibson does that work for archival purposes? I believe we also save the actual webpages themselves already?

**Comment by alexgibson** [comment]
Sorry I have no context for this conversation. Cc’ing @sneethling who I believe is working this.

**Pull request merged**
