### PR TITLE
Legal doc updates

### PR DESCRIPTION
**Pull request by peiying2**
- Thunderbird PN
- Mozilla VPN PN
- Firefox PN
- Legal doc repo Readme.

### CODE REVIEW

**Comment by peiying2** [comment]
@pmac when you get a chance, please take a look where the conflict comes from, so we know what to look for and resolve it ourselves. Thanks!

**Comment by pmac** [comment]
I'm not sure. It looks like you merged `prod` into `master`. I don't think we should ever need to do that.

**Comment by pmac** [comment]
I should be able to fix it. Do you just want what's in `master` currently to go to prod?

**Comment by peiying2** [comment]
> I should be able to fix it. Do you just want what's in `master` currently to go to prod?

Yes please. Thank you.

**Comment by pmac** [comment]
If a new commit comes into master while this is open it'll be included in the PR, just like it would with any other branch. I've pushed an update to the `prod` branch that has brought them into sync. We can close this and hopefully next time it'll be more straight-forward.

**Comment by peiying2** [comment]
> If a new commit comes into master while this is open it'll be included in the PR, just like it would with any other branch. I've pushed an update to the `prod` branch that has brought them into sync. We can close this and hopefully next time it'll be more straight-forward.

Yes, that's what I understood from the "training", documentation. Will make sure the changes goes to master, not in this prod push PR itself. Thank you!

**Pull request merged**
