### PR TITLE
Clarify Cancellation Policy

### PR DESCRIPTION
**Pull request by mafeld**

### CODE REVIEW

**Comment by mafeld** [comment]
@peiying2 - Could you review? I will submit a bug for localization
@pmac - once Peiying approves, could you push to bedrock?

**Review by peiying2 — APPROVED** [review]

**Comment by peiying2** [comment]
@mafeld I approve the PR. Question, will there be date change or version change? Also, is there any other request before the end of the year.

**Comment by mafeld** [comment]
That's a good point. Yes. We should update the date and version.

**Review by peiying2 — APPROVED** [review]

**Comment by pmac** [comment]
Looks like it merged. It's ready to go to the production site?

**Comment by peiying2** [comment]
> Looks like it merged. It's ready to go to the production site?

The revised date on the doc is Dec 23.

**Comment by pmac** [comment]
> The revised date on the doc is Dec 23.

Does that mean we should wait until then to publish?

**Comment by mafeld** [comment]
yes please.

**Pull request merged**
