### PR TITLE
Mention package.json in README

### PR DESCRIPTION
**Pull request by flodolo**
@pdehaan 
Can't flag you as reviewer, but since you were the one who added it, can you chime in?

### CODE REVIEW

**Comment by pdehaan** [comment]
I.... am not sure. At some point (well, 6 years ago, per GitHub history) we added a package.json file so we could add the legal-docs repo as a dependency for mozilla/fxa (or some sub-package). I'll take a quick look and see if we're still trying to ingest all the legal docs that way.

Looks like we're still doing this per [**mozilla/fxa** packages/fxa-content-server/package.json:109](https://github.com/mozilla/fxa/blob/5918b106ba3386cc2b9bbf95d7d66ebe4bc177ce/packages/fxa-content-server/package.json#L109):

> `"legal-docs": "https://github.com/mozilla/legal-docs.git#569f5c812ef288c4ebf19b8d521ba90b99e99cfc",`

But if that's the case, that SHA is like... a year old? https://github.com/mozilla/legal-docs/commit/569f5c812ef288c4ebf19b8d521ba90b99e99cfc

Let me ping @lzoog and see if she knows if this is still the way we import legal stuff or if they've moved on to a different method.

**Comment by pdehaan** [comment]
Per @clouserw we're still using that same workflow of importing the legal files into fxa-content-server:
> _"Your comment is correct afaik.  That SHA needs to be updated when we update legal docs"_

So removing the package.json file here will probably break that import from our side.

**Comment by pdehaan** [comment]
Sorry, was digging a bit more into this and trying to refresh my memory on how this all worked together&hellip;

It's currently being used by fxa-content-server (at least) so we can do `npm install mozilla/legal-docs` and convert the localized `**/firefox_privacy_notice.md` and `**/firefox_cloud_services_tos.md` files to .html (somewhere around https://github.com/mozilla/fxa/blob/d1283314c15d81a85f08dcba5bce329db7c6fd51/packages/fxa-content-server/grunttasks/remarkable.js).

Q: Is there a need to remove the package.json file? If so, we can revisit our current approach and maybe find another way to clone the repo so we can integrate it with our Node.js pipeline.

**Comment by flodolo** [comment]
(cc @clouserw)

Thanks for the pointers, also found this, which helps getting a sense of how this is set up
https://github.com/mozilla/fxa/pull/7077

> Q: Is there a need to remove the package.json file? If so, we can revisit our current approach and maybe find another way to clone the repo so we can integrate it with our Node.js pipeline.

No, but I'm trying to make sense of what's in the repository and why.

This repository has a default branch, and a ` prod` branch. FxA should rely on the `prod` branch, because content updates get sometimes staged for days (if not weeks) before being published. Since nothing is documented, I just potentially broke this workflow by removing `package.json` when pushing to prod.

I understand that the package gets imported. The question is: should it be imported this way? To me, it seems pretty fragile:
1. We import a specific SHA, and someone needs to know it, and manually update that. If nothing else, it should be well documented, and there should be checks in FxA about the SHA not being the latest. Right now, both documents are out of date, since they were updated within the last 3 months.
2. We replicate the conversion that happens on mozilla.org, duplicating with it the risk of issues or bugs in that process. 

To fix 1, would it be possible to point the package to the tip of the prod branch, so it's always up to date?
To fix 2, do we need these documents in FxA? Why is it a problem to link to the official docs hosted on mozilla.org?

**Comment by flodolo** [comment]
Special directives (datetime at the beginning, anchors) show up in the text. Which confirms point 2 above.

https://accounts.firefox.com/legal/terms
https://accounts.firefox.com/legal/privacy

**Comment by flodolo** [comment]
I think 1 is fixable by using `#prod` as a reference, possibly even `mozilla/legal-docs#prod` instead of the full GitHub URL (but I'm not used to deal with JS or Node)
https://docs.npmjs.com/cli/v8/configuring-npm/package-json#github-urls

For 2, you probably want to talk with @pmac and the Bedrock team to replicate what they're doing (probably [this](https://github.com/mozilla/bedrock/blob/67fd925b4d621dde0e48e27738c4b9c397ac5169/bedrock/legal_docs/models.py)?).

@clouserw 
Happy to close this down, add the info to the README on why this file is needed, and file an issue on FxA with this information to fix the current problems. Does that sound reasonable?

**Comment by clouserw** [comment]
Sure.  Thanks @flodolo

**Comment by clouserw** [comment]
and @pdehaan !

**Comment by flodolo** [comment]
https://github.com/mozilla/fxa/issues/12902

I'll use this branch to update the README.

**Pull request merged**
