### PR TITLE
Website PN: update email link for compliance team contact

### PR DESCRIPTION
**Pull request by stevejalim**

### CODE REVIEW

**Comment by stevejalim** [comment]
This is getting eaten by the linter. Will close and try a different tack

**Comment by stevejalim** [comment]
@flod could you help me work out how to keep the linter happy here, please? I see other pages with similar markup, such as  `[hubs@mozilla.com](mailto:hubs@mozilla.com)` in https://github.com/mozilla/legal-docs/blob/282456da1352c957ce57ad214b7b761e3f3cbfcf/en/mozilla_hubs_tos.md?plain=1#L84

**Comment by flodolo** [comment]
The linter is right to be unhappy: you're changing a link in en-US, and it tells you that all the other locales don't have that link (and needs to be updated).

I'll add a commit on top of yours.

**Comment by stevejalim** [comment]
@flod - ah of course. I'd assumed they were magically slotted togehter somehow. My bad.

Thanks for adding the extra changes - very kind of you!

**Review by flodolo — APPROVED** [review]

**Pull request merged**
