### PR TITLE
Update subscription_services_tos.md

### PR DESCRIPTION
**Pull request by craigcook**
Rename "Acceptable Use Policy" and add link.

### CODE REVIEW

**Review by peiying2 — APPROVED** [review]

**Comment by peiying2** [comment]
We may have another update to either this document or a different one. Then we can bundle them together to send out to our translation agency.

**Comment by peiying2** [comment]
@flodolo Looks like @DreaAlexandre created and merged [a different PR](https://github.com/mozilla/legal-docs/pull/2083) for the same change.  

Shall we close this one? Also is this something we can update ourselves or should we send it to HTP?

**Comment by flodolo** [comment]
This one needs to be closed. I need to look into the files to see if I can actually understand where "Conditions of Use" is.

**Comment by craigcook** [comment]
Oops, apologies for the crossed wires.

**Pull request closed without merging**
