### PR TITLE
Update firefox_privacy_notice.md

### PR DESCRIPTION
**Pull request by selimsumlu**
Various corrections

### CODE REVIEW

**Comment by peiying2** [comment]
@selimsumlu thank for taking the time to make all the changes. I will merge the changes. Do me a favor on the changes you made so I can relay to the vendor. I noticed that some are brand/product name related. Beyond that, what are some of the issues: not following the style guide, typo, wrong translation, incorrect use of terminologies?

**Comment by selimsumlu** [comment]
> @selimsumlu thank for taking the time to make all the changes. I will merge the changes. Do me a favor on the changes you made so I can relay to the vendor. I noticed that some are brand/product name related. Beyond that, what are some of the issues: not following the style guide, typo, wrong translation, incorrect use of terminologies?

There were a number of incorrect terms (awesome bar, telemetry, browsing) and one wrong translation. Other than those, I've made some capitalization, punctation and wording changes according my own style (which is not well documented).

**Comment by selimsumlu** [comment]
@peiying2 this hasn't been pushed to production yet. Can you please check if anything has gone wrong?

**Comment by peiying2** [comment]
> @peiying2 this hasn't been pushed to production yet. Can you please check if anything has gone wrong?

According to the record, it was included in this PR merge: https://github.com/mozilla/legal-docs/pull/1688. I checked other docs included in the production push, all the changes have landed except for the `tr` PR.

@flodolo could you check what caused it when you get a chance?

**Comment by flodolo** [comment]
We clearly have some issues with the system to update production. Creating a PR from master to prod doesn't show that change, I think we can only manually port it.

**Comment by peiying2** [comment]
We do have other changes made but they shouldn't go to production until a specific date.

**Comment by flodolo** [comment]
Version on DEV looks correct now. 
https://www-dev.allizom.org/tr/privacy/firefox/

I'm positive I did check that this showed up on prod at the time, so something happened after :-(

**Comment by peiying2** [comment]
@pmac when you get a chance, could you look into this? This PR was included in the production push on Jan 3, all were updated except for this one.

**Comment by peiying2** [comment]
Another question, is it possible to split the updates on master branch and selectively push certain files on production, but not all.

**Comment by pmac** [comment]
> Another question, is it possible to split the updates on master branch and selectively push certain files on production, but not all.

It is possible, but not easy from the GitHub interface. You can ask me and I can make live what you need.

**Comment by pmac** [comment]
so we just need https://github.com/mozilla/legal-docs/commit/bf241f047c12ca69510d86fad61ecb6db2dde28c to go to prod?

**Comment by peiying2** [comment]
> so we just need [bf241f0](https://github.com/mozilla/legal-docs/commit/bf241f047c12ca69510d86fad61ecb6db2dde28c) to go to prod?

Yes, just this one.

**Comment by peiying2** [comment]
> > Another question, is it possible to split the updates on master branch and selectively push certain files on production, but not all.
> 
> It is possible, but not easy from the GitHub interface. You can ask me and I can make live what you need.

Good to know. We will do our best to avoid the situation. Thank you.

**Comment by pmac** [comment]
I have pushed this commit to prod. My apologies for missing whatever caused this reversion.

**Pull request merged**
