### PR TITLE
Spelling and grammatical corrections

### PR DESCRIPTION
**Pull request by upwinxp**

### CODE REVIEW

**Comment by peiying2** [comment]
@upwinxp thank you for the review and corrections. Let me know if you need a peer review of your changes before the merge. Once I get a confirmation from you, I will merge the PR.

Regarding production timeline, there will be another legal doc push soon, I just don't have a schedule as usually the requests are lumped together in one push as long as the change is not urgent.

**Comment by upwinxp** [comment]
I think a review is not necessary as the changes are not major. Adding @mathjazz just in case he'll want to comment on anything.

**Comment by mathjazz** [comment]
r+wc

The only thing I would add in addtion to these changes in make sure that "information" in the context of "personal information" is translated as "podatki" instead of "informacije".

https://sl.linguee.com/angle%C5%A1%C4%8Dina-sloven%C5%A1%C4%8Dina/prevajanje/personal+information.html

**Comment by upwinxp** [comment]
I corrected "informacije" to "podatki" where it was needed. @mathjazz okay?

**Comment by peiying2** [comment]
Thank you for the update. This will go out soon as we had changes in other legal docs.

**Pull request merged**
