### PR TITLE
Update with FreeStar link

### PR DESCRIPTION
**Pull request by mafeld**

### CODE REVIEW

**Review by peiying2 — APPROVED** [review]

**Comment by peiying2** [comment]
@stevejalim not sure where the localized versions live. Want to alert you on the English update.

**Comment by flodolo** [comment]
> @stevejalim not sure where the localized versions live. Want to alert you on the English update.

Are they even localized? This redirects to English
https://getpocket.com/it/privacy/

I don't think the Pocket website is using a different system than the one we use for mozilla.org, which means we don't have a translated version of ToS or PN.

**Comment by peiying2** [comment]
> Are they even localized? This redirects to English https://getpocket.com/it/privacy/
> 
> I don't think the Pocket website is using a different system than the one we use for mozilla.org, which means we don't have a translated version of ToS or PN.

Thanks for checking on this.

**Comment by mafeld** [comment]
Until recently, the Pocket Terms and Privacy notices weren't in our repo. It's new to me that they are. I filed a localization ticket, but I'm not sure how that's currently handled. Do we need to do a full localization now?

**Comment by flodolo** [comment]
https://getpocket.com/en/privacy/ already picked up the change we just merged to prod, so I believe we need to localize them here.

Waiting for Steve to confirm, we'll also need the list of locales.

**Comment by peiying2** [comment]
Steve replied on Slack that Pocket doesn't have localized legal docs.

**Comment by mafeld** [comment]
ok, then yes. Looks like we should localize the whole thing into the same
15 languages as Firefox.
--
Michael Feldman
Product Counsel
***@***.***

**Comment by peiying2** [comment]
They have slightly different set of locales. They have `pt-PT` (Portuguese for Portugal) and fr-CA (Canadian French). Are you ok to consolidate them to `pt-BR` and `fr` respectively?

**Comment by mafeld** [comment]
yes. That's fine.

**Pull request merged**
