### PR TITLE
Removing Adjust reference

### PR DESCRIPTION
**Pull request by litkaemily**
Adjust is no longer being supported for ios; removing this from the privacy notice

### CODE REVIEW

**Comment by litkaemily** [comment]
@pmac Sorry to bother you. I merged this into prod but only seeing it show up in staging? Did I miss a step?

**Comment by pmac** [comment]
it can take a little while for the changes to show up in prod due to data sync time and our CDN cache expiring time. I'll take a look though.

**Comment by pmac** [comment]
I see the updated `September 8` date on https://www.mozilla.org/en-US/privacy/firefox/

**Comment by litkaemily** [comment]
Oh, it must have updated. Apologies. TY for your patience as I continue to learn :)

**Comment by pmac** [comment]
No worries at all. Happy to help.

**Pull request merged**
