### PR TITLE
[FxLite] PN update for adding YouTube DATA API

### PR DESCRIPTION
**Pull request by chianger**

### CODE REVIEW

**Comment by chianger** [comment]
@mafeld could you review this?

**Comment by mafeld** [comment]
This looks right to me. Thanks.

**Comment by peiying2** [comment]
@chianger I will merge this. Let me know if there is l10n need in this. If so, do you have a deadline?

**Comment by chianger** [comment]
> @chianger I will merge this. Let me know if there is l10n need in this. If so, do you have a deadline?
Thank you @peiying2, I was gonna ask for l10n support. We will need localization. Can we have that by Dec-13th end of day?

**Comment by peiying2** [comment]
> Thank you @peiying2, I was gonna ask for l10n support. We will need localization. Can we have that by Dec-13 end of day?
I will take care of it.

**Comment by peiying2** [comment]
@chianger the updates are localized and merged to master. Please follow up with pmac to push the updates to production.

**Pull request merged**
