### PR TITLE
Update Thunderbird privacy notice for OAuth Information

### PR DESCRIPTION
**Pull request by kewisch**

### CODE REVIEW

**Comment by kewisch** [comment]
Errors seem unrelated to my change

**Comment by flodolo** [comment]
The error is indeed unrelated (it needs https://github.com/mozilla/legal-docs/pull/2154).

One thing that is not clear for my team: what's the source of these document updates? Is it our legal department, and this is just a formality, or do they need review from folks like @mafeld?

**Comment by kewisch** [comment]
Sorry for not mentioning. This has been reviewed by Thunderbird's counsel, so it should be good to go. @mafeld did you want to give this an additional review?

**Comment by mafeld** [comment]
This looks good to me

**Review by peiying2 — APPROVED** [review]

**Pull request merged**
