### PR TITLE
bug 1465193 -  [Legal]: doc removal for obsolete products: Hello, Marketplace, Persona

### PR DESCRIPTION
**Pull request by sylvestre**
See https://bugzilla.mozilla.org/show_bug.cgi?id=1465193

### CODE REVIEW

**Comment by peiying2** [comment]
@mikaland2 please confirm if this PR (which I initiated in a bug) is fine to be removed.

**Comment by mikashah** [comment]
Confirming this is fine to remove from current locations and move to the "Outdated Policies" page at: https://www.mozilla.org/privacy/archive/

**Comment by peiying2** [comment]
@sylvestre want to make sure the documents are "archived" somewhere, but removed from this repo so only the docs for active products live here. Just to be sure.

**Comment by peiying2** [comment]
The tasks were done through other means.

**Pull request closed without merging**
