### PR TITLE
Add automation for l10n reviews

### PR DESCRIPTION
**Pull request by flodolo**

### CODE REVIEW

**Comment by flodolo** [comment]
CC @peiying2 

@pmac 
Could you take a look for a general sanity check? Some parts feel a bit hacky, but I'll try to explain the reasoning.

The goal is to keep track of updates to source files (en) that are already translated:
* There's a `l10n_reference` branch, that contains the last translated version of the source files (and only those).
* This GitHub action updates a `l10n_updates` branch, and opens a pull request against `l10n_reference`.

This provides an actual diff of only the source documents and their changes, ignoring all the rest. Once the translation has been delivered, the PR can be merge and the cycle begin from scratch.

The list of files to tracked is stored in the repo (JSON).

`check_status.py` gets some data on the files: 
- List of files that are translate
- List of files that are not translated (en-US only)
- List of files that don't have a matching en-US source

The lists are saved as a README, and the full data is also available as a JSON. This way, it should be easy to spot is something changed also around this (e.g. a brand new file added to en-US).

`cleanup_repository.py` is used to remove all folders and files for the reference l10n branch.

The workflow is a bit hacky:
* I need to manually create the pull request, as a GH action wouldn't be allowed (there isn't an official one from GitHub), but I can use `hub`.
* I can't just start from `master` to create the pull request, because the diff would include ~400 files (mostly removal), and the resulting PR is useless. So, I work around it by copying the files from master in a temp folder, then replacing them on top of `l10n_reference` 🤷🏼 

I've been doing quite a bit of testing on my own fork, and everything seems to work. See for example [this PR](https://github.com/flodolo/legal-docs/pull/12), generated after I added some lines to an existing doc.

**Comment by flodolo** [comment]
BTW, looks like GH shows the README when looking at the branch, since there isn't one in the root https://github.com/mozilla/legal-docs/tree/l10n_reference

**Review by pmac — APPROVED** [review]
Sorry for the delay. I've looked over everything and it seems like it'll work well. I say we give it a shot and continue to monitor and iterate on things as needed. Thanks for all of this work!

**Comment by flodolo** [comment]
Thanks! We have a few incoming requests, so we should be able to test it.

**Pull request merged**
