### PR TITLE
Updating Salesforce -> Acoustic

### PR DESCRIPTION
**Pull request by litkaemily**
Updating Firefox Privacy Notice to reflect that Acoustic is now the email vendor (replacing Salesforce Marketing Cloud)

### CODE REVIEW

**Comment by litkaemily** [comment]
@peiying2 can you help me with this? (cc @pmac)

**Comment by peiying2** [comment]
> @peiying2 can you help me with this? (cc @pmac)

Your PR includes content that already have landed in production: https://github.com/mozilla/legal-docs/pull/1556.

**Comment by peiying2** [comment]
@litkaemily I fixed the conflict from your changes, and the massive changes before yours are now gone (not in the PR anymore). I have merged four more docs from localization. I am waiting for the go-ahead to push them to production. Then we can attempt  to push them with your update together. There might be other issues, we will find out, :).

**Review by peiying2 — APPROVED** [review]

**Comment by peiying2** [comment]
@pmac sorry to bug you. I have several questions:
- What is the issue this time that prevents the merge?
- For future  production push, is it  good practice to make a production  PR soon after the update in master? Or would multiple updates in master branch by different people create conflicts in the phase of production push? 
- When someone is working on a change **before** merging to master, and another person is making a production push, could the subsequent production push attempt create conflict like this one we have now? 

And yes, we need to get this pushed to production.

**Comment by pmac** [comment]
>     * What is the issue this time that prevents the merge?

I'm not sure. Usually this means that something has changed in the branch you're trying to merge into since you made the changes. I'll see what I can find.
 
>     * For future  production push, is it  good practice to make a production  PR soon after the update in master? Or would multiple updates in master branch by different people create conflicts in the phase of production push?

Normally multiple changes is fine. Conflicts usually only occur when the same thing is changed from multiple sources.

>     * When someone is working on a change **before** merging to master, and another person is making a production push, could the subsequent production push attempt create conflict like this one we have now?

I don't think so.

> And yes, we need to get this pushed to production.

I'll work on that too.

**Comment by pmac** [comment]
Oh, in the commits on master I see that you merged "prod" into "master". This could be causing issues. Usually we'd do the opposite.

**Comment by pmac** [comment]
Okay. I manually merged master into prod.

**Comment by peiying2** [comment]
> Oh, in the commits on master I see that you merged "prod" into "master". This could be causing issues. Usually we'd do the opposite.

After I fixed the conflict, the only option was to merge and no other ways to save it, so I clicked the button. I will have you check it next time.

**Comment by peiying2** [comment]
> Okay. I manually merged master into prod.

Thank you for taking the time to do this. Have a good weekend.

**Pull request merged**
