### PR TITLE
HTP_Firefox Privacy Notice Updates_11-26

### PR DESCRIPTION
**Pull request by AdrianUrsea**

### CODE REVIEW

**Comment by flodolo** [comment]
Why are you removing the Relay PN for German in this PR?

As suggested in the past, you should really work on a branch in your fork, then open the pull request from that branch. Your master has a different history from this repository's master, as a consequence each PR contains a lot of unrelated commits, and there's a risk of conflicts/merge errors.

**Comment by peiying2** [comment]
> Why are you removing the Relay PN for German in this PR?
> 
> As suggested in the past, you should really work on a branch in your fork, then open the pull request from that branch. Your master has a different history from this repository's master, as a consequence each PR contains a lot of unrelated commits, and there's a risk of conflicts/merge errors.

I asked them to submit Firefox PN docs only. 

The Relay conflict was the result of all the changes made post their last delivery - to meet the requirement for two releases. The text were there but I had to remove and add content back in. I asked HTP to rebase the Relay so they have the same version as here.

**Comment by flodolo** [comment]
> I asked them to submit Firefox PN docs only.

This PR is literally removing a localized file from the repository (Relay PN for Germany), and that's been in the repo for almost 3 weeks.

**Comment by flodolo** [comment]
I ended up pushing this PR (with the fix) to master by mistake.

@AdrianUrsea 
Please reset your master and work on branches to avoid this type of issues in the future. This should work

```
git remote add upstream https://github.com/mozilla/legal-docs
git fetch upstream
git reset --hard upstream/master
git push -f
```

Once this is done, for the future you can just sync your master with the upstream's master, and keep working on new branches.

**Pull request merged**
