### PR TITLE
Update sumo link for Lite's content & services

### PR DESCRIPTION
**Pull request by chianger**

### CODE REVIEW

**Comment by peiying2** [comment]
@chianger could you update the links for the localized files? This change doesn't need to go to the agency.

**Comment by chianger** [comment]
@peiying2 Yes I can do that. I have to wait until the localized files ready, right? Right now I see those are updated 27 days ago.

**Comment by peiying2** [comment]
> @peiying2 Yes I can do that. I have to wait until the localized files ready, right? Right now I see those are updated 27 days ago.

For this one, there is no l10n need. It was 27 days ago that all the content was updated in the localized versions. The only difference between en-US and the rest is the URL change.

**Comment by chianger** [comment]
> > @peiying2 Yes I can do that. I have to wait until the localized files ready, right? Right now I see those are updated 27 days ago.
> 
> For this one, there is no l10n need. It was 27 days ago that all the content was updated in the localized versions. The only difference between en-US and the rest is the URL change.

Hi @peiying2 
Actually there were some changes last week should be localized if I understand correctly.
https://github.com/mozilla/legal-docs/pull/1383/commits/21f207ea61d006ef6b1009451d23167c57122a17

**Comment by peiying2** [comment]
@chianger for this one, Fx Lite PN, please update the rest of the languages with the URL change. 

For the other one with content change, I will have the update delivered by Tuesday PST time

**Pull request merged**
