### PR TITLE
Update links across documents

### PR DESCRIPTION
**Pull request by flodolo**
- Remove en-US from links to SUMO and mozilla.org, allowing the website to redirect where possible to match the user's preferences.
- Fix a few links still using http://
- Remove a redirected link in Firefox Privacy Notice to SUMO page, use the updated link instead.

### CODE REVIEW

**Comment by flodolo** [comment]
@pmac 

On second thoughts, is this something you'd be OK with checking? I think in the end is more technical than legal:
- I removed "en-US" from all links pointing to SUMO and mozilla.org, so that accept-languages logic can kick in.
- Removed an unnecessary redirect in a SUMO link (Firefox PN).
- Fixed a few old http links, replaced them with https.

This is done in 3 separate commits.

**Comment by flodolo** [comment]
I've actually discovered another type of obsolete links: links to GitHub repository with branch name that changed. Trying to see if I can update those as well.

**Review by pmac — APPROVED** [review]
This all looks good to me. Thanks! 🥇

**Comment by flodolo** [comment]
Thanks.

I'm going to merge this and double check a few documents on stage before pushing it out to production, then I'll jump into the `main` issue.

**Pull request merged**
