### PR TITLE
Update formatting of Hubs privacy doc to be simpler Markdown

### PR DESCRIPTION
**Pull request by stevejalim**
The current formatting of the Hubs Privacy document uses `<details>` tags, which are not parsed correctly by the Bedrock legal-docs importer and also differs from how sibling documents (eg MDN Plus privacy notice) are formatted.

This changeset simplifies the markdown so that the import and rendering works. Below are two screenshots from the Bedrock branch that will support using the updated file once it reaches `main` and `prod`

NB: While the changes are unlikely break any other existing use of the document, it will change the formatting, because it removes the `<details>` markup, which automatically creates expandable sections in some contexts. Eg there were nested `<details>` but I couldn't represent them with a parent `h3` and then child `h4`s, because the CSS for legal docs in bedrock shows `h4`s as very small.

Screenshot 2022-06-12 at 11-06-32 Privacy Notice for Hubs and Spoke

Screenshot 2022-06-12 at 11-06-47 Privacy Notice for Hubs and Spoke

### CODE REVIEW

**Comment by stevejalim** [comment]
Heya @flodolo - what do you think of this? It's one way to solve broken rendering that I see when working on https://github.com/mozilla/bedrock/issues/11711 

If you think amendng the importer is actually the better way to go - eg if we are going to be using <details> more in this repo - please do say and I'll take a different angle.

**Comment by flodolo** [comment]
Makes sense to me not to have HTML markup in a markdown, but I'm not a stakeholder nor a decision maker when it comes to the content of legal docs ;-)

**Comment by stevejalim** [comment]
> Makes sense to me not to have HTML markup in a markdown, but I'm not a stakeholder nor a decision maker when it comes to the content of legal docs ;-)

I've reached out in Slack to see if anyone has info about what surfaces might break if we change the markup, but hoping that @mafeld might know, as he asked for the original work. What do you think, Michael?

**Comment by stevejalim** [comment]
I'm just going to double check that the docs in `mozilla/hubs` haven't drifted from those in this repo - unlikely, I think, but worth a look

**Comment by stevejalim** [comment]
Ah, dangit, looks like there is some difference between the two sets of docs:

| `mozilla/legal-docs` (this) repo | `mozilla/hubs` repo |
| ------ | -------- |
| https://github.com/mozilla/legal-docs/blob/main/en/mozilla_hubs_privacy_notice.md **Date: Version 3.2.3, July 11, 2019** | https://github.com/mozilla/hubs/blob/master/PRIVACY.md **Date: Aug 24, 2021** | 
| https://github.com/mozilla/legal-docs/blob/main/en/mozilla_hubs_privacy_notice.md **Date: Version 3.2, Effective March 12, 2019** | https://github.com/mozilla/hubs/blob/master/TERMS.md **Date: Version 3.4, Effective February 9, 2020** | 

@mafeld Are you happy for me to bring the text from the `mozilla/hubs` documents into this `mozilla/legal-docs` repo, overwriting the current content? I'm happy to make that happen.

**Comment by mafeld** [comment]
@stevejalim Yes please. thanks for catching that.

**Comment by flodolo** [comment]
(please fix the linter issues)

**Review by flodolo — APPROVED** [review]

**Comment by flodolo** [comment]
Going to merge, we can iterate over as needed.

**Pull request merged**
