### PR TITLE
Update report_infringement.md

### PR DESCRIPTION
**Pull request by aroybalreid**
Updating to encourage use of reporting form

### CODE REVIEW

**Review by peiying2 — APPROVED** [review]

**Comment by peiying2** [comment]
@aroybalreid please submit a Jira ticket to initiate the localization request. No need to wait bundle all legal doc updates in one request as they have different language requirement.

**Comment by awmcd** [comment]
@aroybalreid Thanks for submitting! We need to update the form URL, too, to: https://report.mozilla.com/infringement-form

**Comment by aroybalreid** [comment]
@peiying2 - Is there a way we can address Andrew's note (that the URL needs to be corrected) in the same ticket, or do I need to submit another?

**Comment by peiying2** [comment]
> @peiying2 - Is there a way we can address Andrew's note (that the URL needs to be corrected) in the same ticket, or do I need to submit another?

Done!

**Review by flodolo — APPROVED** [review]

**Pull request merged**
