### PR TITLE
Update pocket_privacy_policy.md

### PR DESCRIPTION
**Pull request by aroybalreid**
Per demands from YouTube, policy updated to note that content saved from YouTube would still be hosted on the YouTube website, and subject to the Google Privacy Policy.

### CODE REVIEW

**Review by peiying2 — CHANGES_REQUESTED** [review]
- Date update to this revision
- Missing letter: `... account to. f you use Pocket...` -> `If`

**Comment by aroybalreid** [comment]
1. Please add today's date
2. Please change the requested text to "If..."

**Comment by flodolo** [comment]
@aroybalreid 
You made changes to the branch `main`, which is going to make it very complicated for you going forward. Once we're done with these pending requests, you should delete your fork and fork it again. We can sync on Slack at that point and I'm happy to help.

I'm going to close this PR and put these changes in #2017

**Comment by flodolo** [comment]
One more issue caused by main, luckily caught by @peiying2 

The main branch on the fork is very old, so this update reverted an address update that we made months ago

> This branch is 2 commits ahead of, 104 commits behind mozilla/legal-docs:main.

**Pull request closed without merging**
