### PR TITLE
Add opt out for Mozilla first party tools

### PR DESCRIPTION
**Pull request by mafeld**

### CODE REVIEW

**Review by flodolo — APPROVED** [review]
No issues on my side.

I assume we need to get this localized. Are there other changes that we should group with this, to avoid possible minimum fees?

We also have the pending updates for the locales to cover top 15 languages, as discussed in previous issues.

```
cs/firefox_privacy_notice.md
cs/mozilla_privacy_policy.md
hu/firefox_privacy_notice.md
hu/mozilla_privacy_policy.md
nl/mozilla_privacy_policy.md
```

In case, please file a JIRA request to get the process started.

**Comment by flodolo** [comment]
Note: you can ignore the red "All checks have failed". It's just noting that, with this PR, the localized documents will be missing a link.

**Comment by flodolo** [comment]
@mafeld 
Not sure what's the process here. Should this be merged? Who's going to deploy it to production?

Also, let me know about the pending translation work (see comment above).

**Comment by mafeld** [comment]
Hey @flodolo Sorry for the delay. 
I will file the JIRA localization ticket now. 
If no issues, I'll merge this and file to get it pushed to production. 

Why will the localized documents be missing the link. Since this is a link to control opt outs, we should make sure it's in localized versions. Is there a way to make sure we can do that?

**Comment by flodolo** [comment]
> Why will the localized documents be missing the link. Since this is a link to control opt outs, we should make sure it's in localized versions. Is there a way to make sure we can do that?

Using the locale agnostic link is the correct way, the user will get served the best match based on their option.

For example, if a user asking for en-US content clicks on `https://www.mozilla.org/privacy/websites/data-preferences`, they will end up on `https://www.mozilla.org/en-US/privacy/websites/data-preferences`. Currently, a user asking for French will still end up in the `en-US` page, because there is *no localized* version of that page.

https://github.com/mozilla/bedrock/blob/main/bedrock/privacy/templates/privacy/data-preferences.html

The content is completely hard-coded in the template. If it needs to be localized, that's a conversation to have with the Bedrock team. If exposed for localization, that page will go through the standard channel (vendor for a handful of locales, community for the rest).

**Comment by mafeld** [comment]
Got it. It's an issue of the data preferences page not being localized, so they'll get sent to en-US. thanks

**Comment by flodolo** [comment]
> If no issues, I'll merge this and file to get it pushed to production.

@mafeld 
I don't think this was ever pushed to production? The process is [described here](https://github.com/mozilla/legal-docs#getting-changes-to-production), and it's a lot quicker than it looks.

**Comment by mafeld** [comment]
You're right. that was pretty simple. I have run the production now.
--
Michael Feldman
Product Counsel
***@***.***

**Pull request merged**
